name: build

on: [push, pull_request]

jobs:

  run_test:
    name: test the code
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install pytest
        run: pip install pytest pytest-cov numpy mypy
      - name: type check
        working-directory: ${{github.workspace}}
        run: python -m mypy easy_ast
      - name: run test
        working-directory: ${{github.workspace}}
        run: python -m pytest --cov=easy_ast --cov-fail-under=90

  build_wheels:
    name: build python wheels
    runs-on: ubuntu-latest
    needs: run_test

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install build
        run: python -m pip install build
      - name: build wheel
        working-directory: ${{github.workspace}}
        run: python -m build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/dist/*.whl

  upload_pypi:
    name: upload wheels to pypi
    runs-on: ubuntu-latest
    needs: build_wheels
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: artifact
